### ISSUE TITLE
Concern not extended by ClassMethod

### ISSUE THREAD

**Issue by qnighy** [wantedly/computed_model#36]
Pointed out in https://github.com/wantedly/computed_model/pull/35.

```ruby
require 'computed_model'

module UserConcern
  extend ActiveSupport::Concern
  include ComputedModel::Model

  computed def foo; end
end
```

```
Traceback (most recent call last):
	1: from test.rb:3:in `<main>'
test.rb:7:in `<module:UserConcern>': undefined method `computed' for UserConcern:Module (NoMethodError)
Did you mean?  Complex
```

**Comment by qnighy** [comment]
Filed as https://github.com/rails/rails/issues/42730 while I'm not confident this is an intended use of ActiveSupport::Concern.
